### PR TITLE
Update to MapServer 8.0 syntax and add OGC Features API

### PR DESCRIPTION
**Pull request by geographika**
- Remove keywords that have been deprecated and then removed in v8 of MapServer
- Add layer and web metadata to enable OGC Features API
- Adds FID columns to all datasets (which is why the DBF files have been modified).

### CODE REVIEW

**Comment by geographika** [comment]
Note - this should be merged when the MapServer 8.0 release comes out, or the demo will no longer work. 

Update - it appears the demo site is already using a newer version of MapServer as the following URL is returning an error:

https://demo.mapserver.org/cgi-bin/mapserv?map=%2Fmapserver%2Fapps%2Fitasca_legend%2Fmap%2Fitasca1.map&layers=all&zoomsize=2&zoomdir=1&map_size=600+400

**Comment by geographika** [comment]
Note to work correctly in MapServer 8 the `TEMPLATE` parameter needs to be modifiable from a URL.
See https://github.com/MapServer/MapServer/pull/6469#issuecomment-1375928613

> We'll likely need to expand run-time substitution a little - web->template would be one, layer->mask is another (there was a user request for that one). I was planning on adding those as a commit to this pull request.

**Comment by sdlime** [comment]
> Note to work correctly in MapServer 8 the `TEMPLATE` parameter needs to be modifiable from a URL. See [MapServer/MapServer#6469 (comment)](https://github.com/MapServer/MapServer/pull/6469#issuecomment-1375928613)
> 
> > We'll likely need to expand run-time substitution a little - web->template would be one, layer->mask is another (there was a user request for that one). I was planning on adding those as a commit to this pull request.

I did add layer->mask ahead of 8.0, just missed web->template. Have you run into any others? The demo is pretty old-school and should be a good test.

**Comment by geographika** [comment]
@sdlime - not so far, but I was unable to test much apart from manually updating the TEMPLATE parameter in the Mapfile. I'll hopefully be able to test further on a new OSGeoLive beta, and maybe add a link to the OGC Features.

**Pull request merged**
